# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: acid
  pool: 5
  username: root
  password: Adhi@0000
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: acid_test
  pool: 5
  username: root
  password: Adhi@0000
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: acid_production
  pool: 5
  username: root
  password: Adhi@0000
  socket: /var/run/mysqld/mysqld.sock